### ISSUE TITLE
Refactor Yelp interface

### ISSUE THREAD

**Issue by ianks** [tuxedio/tuxedio-api-legacy#96]
This task should:
1. Implicitly deal with nil cases
2. Stub tests
3. Make Yelp interface more generalizable 
4. Should use be able to use method_missing to access arbitrary aspects of the data (i.e. get_location, get_coordinates, etc)
5. (Possibly) Gem-ify the interface.

**Comment by thejinxters** [comment]
Oh, thank goodness you closed this issue after 9 years 🤣 -- Still miss working with ya @ianks
